- name: Installing stow
  homebrew:
    - name: "stow"
  tags:
    - install
    - dotfiles
    - stow

- name: Installing direnv
  homebrew:
    - name: "direnv"
  tags:
    - install
    - dotfiles
    - direnv

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:horacioh/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./mac
  tags:
    - install
    - dotfiles
    - stow