- name: Installing stow
  community.general.homebrew:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow

- name: Installing direnv
  community.general.homebrew:
    name: direnv
    state: present
  tags:
    - install
    - dotfiles
    - direnv

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:horacioh/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && ./mac
  tags:
    - install
    - dotfiles
    - stow