- name: Install git
  community.general.homebrew:
    name: git
    state: present

- name: Install Github CLI
  community.general.homebrew:
    name: gh
    state: present

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "hi@horacioh.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Horacio Herrera"
  tags:
  - git-personal