- name: Install nodejs and npm
  community.general.homebrew:
    name: node
    state: present
  tags:
    - install
    - node

- name: npmjs prefix
  ansible.builtin.shell: mkdir -p ~/.local/.npm-global
  tags:
  - install
  - node

- name: add npmjs to path
  ansible.builtin.shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node

- name: npmjs global settings
  ansible.builtin.shell: npm config set prefix '~/.local/.npm-global'
  tags:
  - install
  - node

- name: npmjs global settings export path in case I don't have dotfiles installed
  ansible.builtin.shell: export PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node
  - npm-path

- name: Install fnm (node manager)
  ansible.builtin.shell: HOMEBREW_NO_INSTALL_CLEANUP=1 curl -fsSL https://fnm.vercel.app/install | zsh
  tags:
    - install
    - node

- name: Install correct version of Node
  ansible.builtin.shell: fnm install 16
  tags:
    - install
    - node
- name: Installing pnpm
  community.general.homebrew:
    name: pnpm
    state: present
  tags:
    - install
    - node
