- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: >-
      {{ lookup('env', 'HOME')
      }}/.local/share/nvim/site/pack/packer/start/packer.nvim
  tags:
    - install
    - neovim

# not sure why this was not working with the normal homebrew setup...
# running it with shell workes so 🤷‍♂️
- name: Installing neovim
  community.general.homebrew:
    name: neovim
    state: present
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 1
  community.general.homebrew:
    name: luarocks
    state: present
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: true
  ansible.builtin.shell: luarocks install luacheck
  tags:
    - install
    - neovim
